### ISSUE TITLE
ORA-TA fail to execute on MacOS

### ISSUE THREAD

**Issue by Zero-Fanker** [OpenRA-CN/OpenRA#4]
## Issue Summary
ORA - TA fail to execute on MacOS ARM 11.5.1

```
Renderer initialization failed. Check graphics.log for details.
Renderer initialization failed. Check graphics.log for details.
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args) in /Users/fankerzhang/Codes/TiberianAurora/engine/OpenRA.Game/Game.cs:line 327
   at OpenRA.Game.InitializeAndRun(String[] args) in /Users/fankerzhang/Codes/TiberianAurora/engine/OpenRA.Game/Game.cs:line 270
   at OpenRA.Launcher.Program.Main(String[] args) in /Users/fankerzhang/Codes/TiberianAurora/engine/OpenRA.Launcher/Program.cs:line 30
```

## Reproduction
Just run with launch-game.sh

## Expected behavior
It should run normally

**Comment by Zero-Fanker** [comment]
here is the log :

```log
System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libSDL2, 1): image not found
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.CanCreateGLWindow(GLProfile profile) in /Users/ZeroFanker/Codes/TiberianAurora/engine/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 503
   at System.Linq.Enumerable.WhereListIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestEffectiveWindowSize, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile requestProfile, Boolean enableLegacyGL) in /Users/ZeroFanker/Codes/TiberianAurora/engine/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 155
   at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile profile, Boolean enableLegacyGL) in /Users/ZeroFanker/Codes/TiberianAurora/engine/OpenRA.Platforms.Default/DefaultPlatform.cs:line 21
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings) in /Users/ZeroFanker/Codes/TiberianAurora/engine/OpenRA.Game/Renderer.cs:line 78
   at OpenRA.Game.Initialize(Arguments args) in /Users/ZeroFanker/Codes/TiberianAurora/engine/OpenRA.Game/Game.cs:line 347
System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libSDL2, 1): image not found
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.CanCreateGLWindow(GLProfile profile) in /Users/ZeroFanker/Codes/TiberianAurora/engine/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 503
   at System.Linq.Enumerable.WhereListIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestEffectiveWindowSize, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile requestProfile, Boolean enableLegacyGL) in /Users/ZeroFanker/Codes/TiberianAurora/engine/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 155
   at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile profile, Boolean enableLegacyGL) in /Users/ZeroFanker/Codes/TiberianAurora/engine/OpenRA.Platforms.Default/DefaultPlatform.cs:line 21
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings) in /Users/ZeroFanker/Codes/TiberianAurora/engine/OpenRA.Game/Renderer.cs:line 78
   at OpenRA.Game.Initialize(Arguments args) in /Users/ZeroFanker/Codes/TiberianAurora/engine/OpenRA.Game/Game.cs:line 347

```
